"""Indian festival dates (Telugu calendar), seeded from festivals_telugu.json.

The JSON is generated by scripts/gen_festival_dates.py. Rows the user edited
are never overwritten.
"""

import json
from datetime import date
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.orm import Session

from ..models import FestivalDate

TABLE = Path(__file__).with_name("festivals_telugu.json")

FESTIVALS: dict[str, str] = {
    "sankranti": "Sankranti",
    "ugadi": "Ugadi",
    "holi": "Holi",
    "raksha_bandhan": "Raksha Bandhan",
    "ganesh_chaturthi": "Ganesh Chaturthi",
    "dussehra": "Dussehra",
    "diwali": "Deepavali",
}

# Shown under the date range, e.g. "Bhogi – Kanuma"
RANGE_NOTE: dict[str, str] = {
    "sankranti": "Bhogi, Sankranti & Kanuma",
    "holi": "Holika Dahan & Holi",
    "diwali": "Naraka Chaturdashi & Deepavali",
}


def builtin_table() -> dict[str, dict[str, dict]]:
    return json.loads(TABLE.read_text())["festivals"]


def seed_festivals(s: Session) -> int:
    """Insert built-in dates that are missing. Returns rows added."""
    have = set(s.execute(select(FestivalDate.festival, FestivalDate.year)).all())
    added = 0
    for key, years in builtin_table().items():
        for y, entry in years.items():
            if (key, int(y)) in have:
                continue
            day = date.fromisoformat(entry["date"])
            s.add(
                FestivalDate(
                    festival=key,
                    year=int(y),
                    date=day,
                    start=date.fromisoformat(entry.get("start", entry["date"])),
                    end=date.fromisoformat(entry.get("end", entry["date"])),
                )
            )
            added += 1
    s.commit()
    return added


def reset_festival(s: Session, row: FestivalDate) -> FestivalDate:
    """Restore a row to the built-in date."""
    entry = builtin_table()[row.festival][str(row.year)]
    row.date = date.fromisoformat(entry["date"])
    row.start = date.fromisoformat(entry.get("start", entry["date"]))
    row.end = date.fromisoformat(entry.get("end", entry["date"]))
    row.user_edited = False
    s.commit()
    return row
